CREATE_RECIPE_MAIN_INGREDIENTS = 1
CREATE_RECIPE_SECONDARY_INGREDIENTS = 2
CREATE_RECIPE_STEP_BY_STEP = 3
CREATE_RECIPE_IMAGE = 4
CREATE_RECIPE_LINK = 5
CREATE_RECIPE_CHECK = 6
CREATE_RECIPE_CONFIRMATION = 7
